name: Python CI  #name of the workflow

#Trigger the workflow on any push to the amin branch or pull request
on:
  push:  #Event
    branches: #Can add more than one branches
      - main
  pull_request:  #Event
    branches:
      - main

#github provides different containers like ubuntu-latest, windows,mac
jobs:
  test:  
    runs-on: ubuntu-latest #It means on which container we want to run our test cases

    steps:
      # Step -1: Chech out the code from repository 
      - name: Check out code 
        uses: actions/checkout@v2 #it triggers an event where we take the code from the repository and we check it out so that it can be moved to the container and then tested

      # Step 2: Set up a python envioronment 
      - name: Set up Python
        uses: actions/setup-python@v2  # this github action triggers a event in which a new envioronment is created
        with:
          python-version: '3.8'
        
      #Step 3:Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #Step 4: Run Tests
      - name: Run tests
        run: pytest # Whenever this called in the container it will look for the tests folder and run the tests cases
        
